title: 铅岛酱
description: My Personal Blog
author: XiaoqianSHEN
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/XiaoqianSHEN
about: ZhengshuaiPeng's WIFI

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: 
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]